spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backendninja-contacts?serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false